-- +goose Up
INSERT INTO movie_genre (movie_id, genre_id) VALUES 
((SELECT id FROM movie where title = '99 Songs'), (SELECT id from genre where name = 'Romance')),
((SELECT id FROM movie where title = 'Karnan'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Karnan'), (SELECT id from genre where name = 'Action')),
((SELECT id FROM movie where title = '99 Songs'), (SELECT id from genre where name = 'Musical')),
((SELECT id FROM movie where title = 'Star Wars: Episode V - The Empire Strikes Back'), (SELECT id from genre where name = 'Adventure')),
((SELECT id FROM movie where title = 'Star Wars: Episode V - The Empire Strikes Back'), (SELECT id from genre where name = 'Sci-Fi')),
((SELECT id FROM movie where title = 'Star Wars: Episode V - The Empire Strikes Back'), (SELECT id from genre where name = 'Fantasy')),
((SELECT id FROM movie where title = 'Star Wars: Episode V - The Empire Strikes Back'), (SELECT id from genre where name = 'Action')),
((SELECT id FROM movie where title = 'The Lord of the Rings: The Return of the King'), (SELECT id from genre where name = 'Adventure')),
((SELECT id FROM movie where title = 'The Lord of the Rings: The Return of the King'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'The Lord of the Rings: The Return of the King'), (SELECT id from genre where name = 'Fantasy')),
((SELECT id FROM movie where title = 'The Lord of the Rings: The Return of the King'), (SELECT id from genre where name = 'Action')),
((SELECT id FROM movie where title = 'One Flew Over the Cuckoo''s Nest'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'David Attenborough: A Life on Our Planet'), (SELECT id from genre where name = 'Biography')),
((SELECT id FROM movie where title = 'David Attenborough: A Life on Our Planet'), (SELECT id from genre where name = 'Documentary')),
((SELECT id FROM movie where title = 'Banshee'), (SELECT id from genre where name = 'Action')),
((SELECT id FROM movie where title = 'Gisaengchung'), (SELECT id from genre where name = 'Comedy')),
((SELECT id FROM movie where title = 'Gisaengchung'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Gisaengchung'), (SELECT id from genre where name = 'Thriller')),
((SELECT id FROM movie where title = 'Il buono, il brutto, il cattivo'), (SELECT id from genre where name = 'Western')),
((SELECT id FROM movie where title = 'Dag II'), (SELECT id from genre where name = 'Action')),
((SELECT id FROM movie where title = 'Dag II'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Dag II'), (SELECT id from genre where name = 'War')),
((SELECT id FROM movie where title = 'Les Misérables in Concert: The 25th Anniversary'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Les Misérables in Concert: The 25th Anniversary'), (SELECT id from genre where name = 'Musical')),
((SELECT id FROM movie where title = 'Les Misérables in Concert: The 25th Anniversary'), (SELECT id from genre where name = 'Music')),
((SELECT id FROM movie where title = 'The Six'), (SELECT id from genre where name = 'Documentary')),
((SELECT id FROM movie where title = 'The Get Together'), (SELECT id from genre where name = 'Comedy')),
((SELECT id FROM movie where title = 'The Godfather: Part II'), (SELECT id from genre where name = 'Crime')),
((SELECT id FROM movie where title = 'The Godfather: Part II'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Pariyerum Perumal'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Baraka'), (SELECT id from genre where name = 'Documentary')),
((SELECT id FROM movie where title = 'Forrest Gump'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Forrest Gump'), (SELECT id from genre where name = 'Romance')),
((SELECT id FROM movie where title = 'Initiation'), (SELECT id from genre where name = 'Crime')),
((SELECT id FROM movie where title = 'Initiation'), (SELECT id from genre where name = 'Thriller')),
((SELECT id FROM movie where title = 'Initiation'), (SELECT id from genre where name = 'Mystery')),
((SELECT id FROM movie where title = 'Initiation'), (SELECT id from genre where name = 'Horror')),
((SELECT id FROM movie where title = 'Dominion'), (SELECT id from genre where name = 'Documentary')),
((SELECT id FROM movie where title = 'Saving Private Ryan'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Saving Private Ryan'), (SELECT id from genre where name = 'War')),
((SELECT id FROM movie where title = 'Sen to Chihiro no kamikakushi'), (SELECT id from genre where name = 'Adventure')),
((SELECT id FROM movie where title = 'Sen to Chihiro no kamikakushi'), (SELECT id from genre where name = 'Family')),
((SELECT id FROM movie where title = 'Sen to Chihiro no kamikakushi'), (SELECT id from genre where name = 'Animation')),
((SELECT id FROM movie where title = 'Sen to Chihiro no kamikakushi'), (SELECT id from genre where name = 'Fantasy')),
((SELECT id FROM movie where title = 'The Silence of the Lambs'), (SELECT id from genre where name = 'Crime')),
((SELECT id FROM movie where title = 'The Silence of the Lambs'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'C/o Kancharapalem'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Sen to Chihiro no kamikakushi'), (SELECT id from genre where name = 'Mystery')),
((SELECT id FROM movie where title = 'Goodfellas'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Goodfellas'), (SELECT id from genre where name = 'Crime')),
((SELECT id FROM movie where title = 'The Silence of the Lambs'), (SELECT id from genre where name = 'Thriller')),
((SELECT id FROM movie where title = 'Goodfellas'), (SELECT id from genre where name = 'Biography')),
((SELECT id FROM movie where title = 'The Godfather'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'The Godfather'), (SELECT id from genre where name = 'Crime')),
((SELECT id FROM movie where title = 'Kill Bill: The Whole Bloody Affair'), (SELECT id from genre where name = 'Crime')),
((SELECT id FROM movie where title = 'Kill Bill: The Whole Bloody Affair'), (SELECT id from genre where name = 'Action')),
((SELECT id FROM movie where title = 'Kill Bill: The Whole Bloody Affair'), (SELECT id from genre where name = 'Thriller')),
((SELECT id FROM movie where title = 'The Dark Knight'), (SELECT id from genre where name = 'Crime')),
((SELECT id FROM movie where title = 'The Dark Knight'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'The Dark Knight'), (SELECT id from genre where name = 'Action')),
((SELECT id FROM movie where title = 'The Dark Knight'), (SELECT id from genre where name = 'Thriller')),
((SELECT id FROM movie where title = 'The Lord of the Rings: The Two Towers'), (SELECT id from genre where name = 'Fantasy')),
((SELECT id FROM movie where title = 'The Lord of the Rings: The Two Towers'), (SELECT id from genre where name = 'Adventure')),
((SELECT id FROM movie where title = 'The Lord of the Rings: The Two Towers'), (SELECT id from genre where name = 'Action')),
((SELECT id FROM movie where title = 'The Lord of the Rings: The Two Towers'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Interstellar'), (SELECT id from genre where name = 'Adventure')),
((SELECT id FROM movie where title = 'Interstellar'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Interstellar'), (SELECT id from genre where name = 'Sci-Fi')),
((SELECT id FROM movie where title = 'Fight Club'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Soorarai Pottru'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'La vita è bella'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'La vita è bella'), (SELECT id from genre where name = 'Romance')),
((SELECT id FROM movie where title = 'La vita è bella'), (SELECT id from genre where name = 'War')),
((SELECT id FROM movie where title = 'La vita è bella'), (SELECT id from genre where name = 'Comedy')),
((SELECT id FROM movie where title = 'O.J.: Made in America'), (SELECT id from genre where name = 'Crime')),
((SELECT id FROM movie where title = 'O.J.: Made in America'), (SELECT id from genre where name = 'Biography')),
((SELECT id FROM movie where title = 'O.J.: Made in America'), (SELECT id from genre where name = 'History')),
((SELECT id FROM movie where title = 'O.J.: Made in America'), (SELECT id from genre where name = 'Documentary')),
((SELECT id FROM movie where title = 'Se7en'), (SELECT id from genre where name = 'Crime')),
((SELECT id FROM movie where title = 'Se7en'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Se7en'), (SELECT id from genre where name = 'Thriller')),
((SELECT id FROM movie where title = 'Se7en'), (SELECT id from genre where name = 'Mystery')),
((SELECT id FROM movie where title = 'The Lord of the Rings: The Fellowship of the Ring'), (SELECT id from genre where name = 'Adventure')),
((SELECT id FROM movie where title = 'The Lord of the Rings: The Fellowship of the Ring'), (SELECT id from genre where name = 'Fantasy')),
((SELECT id FROM movie where title = 'The Lord of the Rings: The Fellowship of the Ring'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'The Lord of the Rings: The Fellowship of the Ring'), (SELECT id from genre where name = 'Action')),
((SELECT id FROM movie where title = 'Drishyam 2'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Drishyam 2'), (SELECT id from genre where name = 'Crime')),
((SELECT id FROM movie where title = 'Drishyam 2'), (SELECT id from genre where name = 'Thriller')),
((SELECT id FROM movie where title = 'Kumbalangi Nights'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Kumbalangi Nights'), (SELECT id from genre where name = 'Comedy')),
((SELECT id FROM movie where title = 'Kumbalangi Nights'), (SELECT id from genre where name = 'Romance')),
((SELECT id FROM movie where title = '96'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = '96'), (SELECT id from genre where name = 'Romance')),
((SELECT id FROM movie where title = 'Pulp Fiction'), (SELECT id from genre where name = 'Crime')),
((SELECT id FROM movie where title = 'Pulp Fiction'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Seppuku'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Seppuku'), (SELECT id from genre where name = 'Mystery')),
((SELECT id FROM movie where title = 'Seppuku'), (SELECT id from genre where name = 'Action')),
((SELECT id FROM movie where title = 'Inception'), (SELECT id from genre where name = 'Adventure')),
((SELECT id FROM movie where title = 'Inception'), (SELECT id from genre where name = 'Action')),
((SELECT id FROM movie where title = 'Inception'), (SELECT id from genre where name = 'Sci-Fi')),
((SELECT id FROM movie where title = 'Inception'), (SELECT id from genre where name = 'Thriller')),
((SELECT id FROM movie where title = 'The Shawshank Redemption'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Star Wars'), (SELECT id from genre where name = 'Adventure')),
((SELECT id FROM movie where title = 'Star Wars'), (SELECT id from genre where name = 'Fantasy')),
((SELECT id FROM movie where title = 'Star Wars'), (SELECT id from genre where name = 'Sci-Fi')),
((SELECT id FROM movie where title = 'Star Wars'), (SELECT id from genre where name = 'Action')),
((SELECT id FROM movie where title = 'Earthlings'), (SELECT id from genre where name = 'Documentary')),
((SELECT id FROM movie where title = 'National Theatre Live: Frankenstein'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'National Theatre Live: Frankenstein'), (SELECT id from genre where name = 'Sci-Fi')),
((SELECT id FROM movie where title = 'The Green Mile'), (SELECT id from genre where name = 'Fantasy')),
((SELECT id FROM movie where title = 'The Green Mile'), (SELECT id from genre where name = 'Crime')),
((SELECT id FROM movie where title = 'The Green Mile'), (SELECT id from genre where name = 'Mystery')),
((SELECT id FROM movie where title = 'The Green Mile'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Schindler''s List'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Schindler''s List'), (SELECT id from genre where name = 'History')),
((SELECT id FROM movie where title = 'Schindler''s List'), (SELECT id from genre where name = 'Biography')),
((SELECT id FROM movie where title = 'Cidade de Deus'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Cidade de Deus'), (SELECT id from genre where name = 'Crime')),
((SELECT id FROM movie where title = 'Anbe Sivam'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Anbe Sivam'), (SELECT id from genre where name = 'Adventure')),
((SELECT id FROM movie where title = 'Anbe Sivam'), (SELECT id from genre where name = 'Comedy')),
((SELECT id FROM movie where title = 'The Matrix'), (SELECT id from genre where name = 'Sci-Fi')),
((SELECT id FROM movie where title = 'The Matrix'), (SELECT id from genre where name = 'Action')),
((SELECT id FROM movie where title = 'Intouchables'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Intouchables'), (SELECT id from genre where name = 'Comedy')),
((SELECT id FROM movie where title = 'Intouchables'), (SELECT id from genre where name = 'Biography')),
((SELECT id FROM movie where title = 'Cousins'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Back to the Future'), (SELECT id from genre where name = 'Adventure')),
((SELECT id FROM movie where title = 'Back to the Future'), (SELECT id from genre where name = 'Comedy')),
((SELECT id FROM movie where title = 'Back to the Future'), (SELECT id from genre where name = 'Sci-Fi')),
((SELECT id FROM movie where title = 'Nuovo Cinema Paradiso'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Nuovo Cinema Paradiso'), (SELECT id from genre where name = 'Romance')),
((SELECT id FROM movie where title = 'Whiplash'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Whiplash'), (SELECT id from genre where name = 'Music')),
((SELECT id FROM movie where title = 'Avengers: Endgame'), (SELECT id from genre where name = 'Adventure')),
((SELECT id FROM movie where title = 'Avengers: Endgame'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Avengers: Endgame'), (SELECT id from genre where name = 'Sci-Fi')),
((SELECT id FROM movie where title = 'Avengers: Endgame'), (SELECT id from genre where name = 'Action')),
((SELECT id FROM movie where title = 'American History X'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Gladiator'), (SELECT id from genre where name = 'Adventure')),
((SELECT id FROM movie where title = 'Gladiator'), (SELECT id from genre where name = 'Action')),
((SELECT id FROM movie where title = 'Gladiator'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'The Usual Suspects'), (SELECT id from genre where name = 'Crime')),
((SELECT id FROM movie where title = 'The Usual Suspects'), (SELECT id from genre where name = 'Mystery')),
((SELECT id FROM movie where title = 'The Usual Suspects'), (SELECT id from genre where name = 'Thriller')),
((SELECT id FROM movie where title = 'The Mitchells vs. the Machines'), (SELECT id from genre where name = 'Adventure')),
((SELECT id FROM movie where title = 'The Mitchells vs. the Machines'), (SELECT id from genre where name = 'Family')),
((SELECT id FROM movie where title = 'The Mitchells vs. the Machines'), (SELECT id from genre where name = 'Sci-Fi')),
((SELECT id FROM movie where title = 'The Mitchells vs. the Machines'), (SELECT id from genre where name = 'Animation')),
((SELECT id FROM movie where title = 'The Mitchells vs. the Machines'), (SELECT id from genre where name = 'Comedy')),
((SELECT id FROM movie where title = 'Mandela'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Mandela'), (SELECT id from genre where name = 'Comedy')),
((SELECT id FROM movie where title = 'National Theatre Live: Coriolanus'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'National Theatre Live: Coriolanus'), (SELECT id from genre where name = 'War')),
((SELECT id FROM movie where title = 'National Theatre Live: Coriolanus'), (SELECT id from genre where name = 'History')),
((SELECT id FROM movie where title = 'Black Friday'), (SELECT id from genre where name = 'Crime')),
((SELECT id FROM movie where title = 'Black Friday'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Black Friday'), (SELECT id from genre where name = 'Action')),
((SELECT id FROM movie where title = 'Black Friday'), (SELECT id from genre where name = 'History')),
((SELECT id FROM movie where title = 'Django Unchained'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Django Unchained'), (SELECT id from genre where name = 'Western')),
((SELECT id FROM movie where title = 'Senna'), (SELECT id from genre where name = 'Sport')),
((SELECT id FROM movie where title = 'Senna'), (SELECT id from genre where name = 'Biography')),
((SELECT id FROM movie where title = 'Senna'), (SELECT id from genre where name = 'Documentary')),
((SELECT id FROM movie where title = 'Dear Zachary: A Letter to a Son About His Father'), (SELECT id from genre where name = 'Crime')),
((SELECT id FROM movie where title = 'Dear Zachary: A Letter to a Son About His Father'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Dear Zachary: A Letter to a Son About His Father'), (SELECT id from genre where name = 'Biography')),
((SELECT id FROM movie where title = 'Dear Zachary: A Letter to a Son About His Father'), (SELECT id from genre where name = 'Documentary')),
((SELECT id FROM movie where title = 'The Prestige'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'The Prestige'), (SELECT id from genre where name = 'Thriller')),
((SELECT id FROM movie where title = 'The Prestige'), (SELECT id from genre where name = 'Sci-Fi')),
((SELECT id FROM movie where title = 'The Prestige'), (SELECT id from genre where name = 'Mystery')),
((SELECT id FROM movie where title = 'Psycho'), (SELECT id from genre where name = 'Thriller')),
((SELECT id FROM movie where title = 'Psycho'), (SELECT id from genre where name = 'Horror')),
((SELECT id FROM movie where title = 'Psycho'), (SELECT id from genre where name = 'Mystery')),
((SELECT id FROM movie where title = 'Alien'), (SELECT id from genre where name = 'Sci-Fi')),
((SELECT id FROM movie where title = 'Alien'), (SELECT id from genre where name = 'Horror')),
((SELECT id FROM movie where title = 'The Lion King'), (SELECT id from genre where name = 'Adventure')),
((SELECT id FROM movie where title = 'The Lion King'), (SELECT id from genre where name = 'Family')),
((SELECT id FROM movie where title = 'The Lion King'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'The Lion King'), (SELECT id from genre where name = 'Musical')),
((SELECT id FROM movie where title = 'The Lion King'), (SELECT id from genre where name = 'Animation')),
((SELECT id FROM movie where title = 'Sir Alex Ferguson: Never Give In'), (SELECT id from genre where name = 'Documentary')),
((SELECT id FROM movie where title = 'The Dark Knight Rises'), (SELECT id from genre where name = 'Adventure')),
((SELECT id FROM movie where title = 'The Dark Knight Rises'), (SELECT id from genre where name = 'Action')),
((SELECT id FROM movie where title = 'The Salt of the Earth'), (SELECT id from genre where name = 'Biography')),
((SELECT id FROM movie where title = 'The Salt of the Earth'), (SELECT id from genre where name = 'History')),
((SELECT id FROM movie where title = 'The Salt of the Earth'), (SELECT id from genre where name = 'Documentary')),
((SELECT id FROM movie where title = 'The Shining'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'The Shining'), (SELECT id from genre where name = 'Horror')),
((SELECT id FROM movie where title = 'Léon'), (SELECT id from genre where name = 'Action')),
((SELECT id FROM movie where title = 'Léon'), (SELECT id from genre where name = 'Thriller')),
((SELECT id FROM movie where title = 'Léon'), (SELECT id from genre where name = 'Crime')),
((SELECT id FROM movie where title = 'Léon'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Hotaru no haka'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Hotaru no haka'), (SELECT id from genre where name = 'Animation')),
((SELECT id FROM movie where title = 'Hotaru no haka'), (SELECT id from genre where name = 'War')),
((SELECT id FROM movie where title = 'Hamilton'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Hamilton'), (SELECT id from genre where name = 'Biography')),
((SELECT id FROM movie where title = 'Hamilton'), (SELECT id from genre where name = 'History')),
((SELECT id FROM movie where title = 'Hamilton'), (SELECT id from genre where name = 'Musical')),
((SELECT id FROM movie where title = 'Ratsasan'), (SELECT id from genre where name = 'Crime')),
((SELECT id FROM movie where title = 'Ratsasan'), (SELECT id from genre where name = 'Thriller')),
((SELECT id FROM movie where title = 'Ratsasan'), (SELECT id from genre where name = 'Action')),
((SELECT id FROM movie where title = 'Samsara'), (SELECT id from genre where name = 'Music')),
((SELECT id FROM movie where title = 'Samsara'), (SELECT id from genre where name = 'Documentary')),
((SELECT id FROM movie where title = 'Joker'), (SELECT id from genre where name = 'Crime')),
((SELECT id FROM movie where title = 'Joker'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Joker'), (SELECT id from genre where name = 'Thriller')),
((SELECT id FROM movie where title = 'The Mole: Undercover in North Korea'), (SELECT id from genre where name = 'Thriller')),
((SELECT id FROM movie where title = 'Capharnaüm'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'The Mole: Undercover in North Korea'), (SELECT id from genre where name = 'Documentary')),
((SELECT id FROM movie where title = 'C''era una volta il West'), (SELECT id from genre where name = 'Western')),
((SELECT id FROM movie where title = 'Jersey'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Jersey'), (SELECT id from genre where name = 'Sport')),
((SELECT id FROM movie where title = 'Suna no onna'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Suna no onna'), (SELECT id from genre where name = 'Thriller')),
((SELECT id FROM movie where title = 'Mononoke-hime'), (SELECT id from genre where name = 'Adventure')),
((SELECT id FROM movie where title = 'Mononoke-hime'), (SELECT id from genre where name = 'Fantasy')),
((SELECT id FROM movie where title = 'Mononoke-hime'), (SELECT id from genre where name = 'Animation')),
((SELECT id FROM movie where title = 'Mononoke-hime'), (SELECT id from genre where name = 'Action')),
((SELECT id FROM movie where title = 'WALL·E'), (SELECT id from genre where name = 'Adventure')),
((SELECT id FROM movie where title = 'WALL·E'), (SELECT id from genre where name = 'Family')),
((SELECT id FROM movie where title = 'WALL·E'), (SELECT id from genre where name = 'Animation')),
((SELECT id FROM movie where title = 'WALL·E'), (SELECT id from genre where name = 'Romance')),
((SELECT id FROM movie where title = 'WALL·E'), (SELECT id from genre where name = 'Sci-Fi')),
((SELECT id FROM movie where title = 'Visaaranai'), (SELECT id from genre where name = 'Crime')),
((SELECT id FROM movie where title = 'Visaaranai'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Visaaranai'), (SELECT id from genre where name = 'Thriller')),
((SELECT id FROM movie where title = 'Das Leben der Anderen'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Das Leben der Anderen'), (SELECT id from genre where name = 'Mystery')),
((SELECT id FROM movie where title = 'Das Leben der Anderen'), (SELECT id from genre where name = 'Thriller')),
((SELECT id FROM movie where title = 'Apocalypse Now'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'Apocalypse Now'), (SELECT id from genre where name = 'Mystery')),
((SELECT id FROM movie where title = 'Apocalypse Now'), (SELECT id from genre where name = 'War')),
((SELECT id FROM movie where title = 'The Departed'), (SELECT id from genre where name = 'Crime')),
((SELECT id FROM movie where title = 'The Departed'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'The Departed'), (SELECT id from genre where name = 'Thriller')),
((SELECT id FROM movie where title = 'La meglio gioventù'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'La meglio gioventù'), (SELECT id from genre where name = 'Romance')),
((SELECT id FROM movie where title = 'Kimetsu no Yaiba: Mugen Ressha-Hen'), (SELECT id from genre where name = 'Adventure')),
((SELECT id FROM movie where title = 'Kimetsu no Yaiba: Mugen Ressha-Hen'), (SELECT id from genre where name = 'Animation')),
((SELECT id FROM movie where title = 'Kimetsu no Yaiba: Mugen Ressha-Hen'), (SELECT id from genre where name = 'Fantasy')),
((SELECT id FROM movie where title = 'Kimetsu no Yaiba: Mugen Ressha-Hen'), (SELECT id from genre where name = 'Action')),
((SELECT id FROM movie where title = 'Disney''s Newsies: The Broadway Musical'), (SELECT id from genre where name = 'Musical')),
((SELECT id FROM movie where title = 'Terminator 2: Judgment Day'), (SELECT id from genre where name = 'Sci-Fi')),
((SELECT id FROM movie where title = 'Terminator 2: Judgment Day'), (SELECT id from genre where name = 'Action')),
((SELECT id FROM movie where title = 'For Sama'), (SELECT id from genre where name = 'War')),
((SELECT id FROM movie where title = 'For Sama'), (SELECT id from genre where name = 'Documentary')),
((SELECT id FROM movie where title = 'Avengers: Infinity War'), (SELECT id from genre where name = 'Adventure')),
((SELECT id FROM movie where title = 'Avengers: Infinity War'), (SELECT id from genre where name = 'Sci-Fi')),
((SELECT id FROM movie where title = 'Avengers: Infinity War'), (SELECT id from genre where name = 'Action')),
((SELECT id FROM movie where title = 'Memento'), (SELECT id from genre where name = 'Thriller')),
((SELECT id FROM movie where title = 'Memento'), (SELECT id from genre where name = 'Mystery')),
((SELECT id FROM movie where title = 'Spider-Man: Into the Spider-Verse'), (SELECT id from genre where name = 'Adventure')),
((SELECT id FROM movie where title = 'Spider-Man: Into the Spider-Verse'), (SELECT id from genre where name = 'Sci-Fi')),
((SELECT id FROM movie where title = 'Spider-Man: Into the Spider-Verse'), (SELECT id from genre where name = 'Animation')),
((SELECT id FROM movie where title = 'Spider-Man: Into the Spider-Verse'), (SELECT id from genre where name = 'Action')),
((SELECT id FROM movie where title = 'Spider-Man: Into the Spider-Verse'), (SELECT id from genre where name = 'Family')),
((SELECT id FROM movie where title = 'The Pianist'), (SELECT id from genre where name = 'Drama')),
((SELECT id FROM movie where title = 'The Pianist'), (SELECT id from genre where name = 'Biography')),
((SELECT id FROM movie where title = 'The Pianist'), (SELECT id from genre where name = 'War')),
((SELECT id FROM movie where title = 'The Pianist'), (SELECT id from genre where name = 'Music'));